TaskManagerLaravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();


// Routes accessible only to admins and managers
Route::middleware(['auth', 'manager'])->group(function () {
    // Project Routes
    Route::get('projects/create', 'ProjectController@create')->name('projects.create');
    Route::post('projects', 'ProjectController@store')->name('projects.store');
    Route::put('projects/{project}', 'ProjectController@update')->name('projects.update');
    Route::delete('projects/{project}', 'ProjectController@destroy')->name('projects.destroy');
    Route::get('projects/{project}/edit', 'ProjectController@edit')->name('projects.edit');

    Route::get('users', 'UserController@index')->name('users.index');
});




// Routes accessible to all authenticated users
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    // User route seems not to work if put in the user routes section
    Route::get('users/profile', 'UserController@editProfile')->name('users.edit-profile');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::get('users/notifications', 'UserController@notifications')->name('users.notifications');

    Route::get('projects', 'ProjectController@index')->name('projects.index');
    Route::get('projects/{project}', 'ProjectController@show')->name('projects.show');

    // Task Routes
    Route::get('tasks', 'TaskController@index')->name('tasks.index');
    Route::post('tasks', 'TaskController@store')->name('tasks.store');
    Route::get('tasks/create', 'TaskController@create')->name('tasks.create');
    Route::delete('tasks/{task}', 'TaskController@destroy')->name('tasks.destroy');
    Route::get('tasks/{task}', 'TaskController@show')->name('tasks.show');
    Route::put('tasks/{task}', 'TaskController@update')->name('tasks.update');
    Route::get('tasks/{task}/edit', 'TaskController@edit')->name('tasks.edit');

    // Tag Routes
    Route::resource('tags', 'TagController');
    Route::resource('comments', 'CommentController');

    // User Routes
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
});

// Routes accessible only to the admins
//Route::middleware(['auth', 'admin'])->group(function () {
//});
//
//

TaskManagerLaravel/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    @yield('css')
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('projects') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item">
                                <a href="{{ route('users.notifications') }}" class="nav-link">
                                    <span class="badge" style="color: white; background: steelblue;">
                                    @if (auth()->user()->unreadNotifications->count() == 1)
                                            {{ auth()->user()->unreadNotifications->count() }} Unread notification
                                        @else
                                            {{ auth()->user()->unreadNotifications->count() }} Unread notifications
                                        @endif
                                </span>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('users.show', auth()->user()) }}">Profile</a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @auth
                <div class="container">
                    @if(session()->has('success'))
                        <div class="alert alert-success">
                            {{ session()->get('success') }}
                        </div>
                    @endif
                    @if(session()->has('error'))
                        <div class="alert alert-danger">
                            {{ session()->get('error') }}
                        </div>
                    @endif
                    <div class="row">
                        <div class="col-md-2">
                            <ul class="list-group">
                                @if(auth()->user()->isAdmin() || auth()->user()->isManager())
                                <li class="list-group-item">
                                    <a href="{{ route('users.index') }}">Users</a>
                                </li>
                                @endif
                                <li class="list-group-item">
                                    <a href="{{ route('projects.index') }}">Projects</a>
                                </li>
                                <li class="list-group-item">
                                    <a href="{{ route('tasks.index') }}">Tasks</a>
                                </li>
                                <li class="list-group-item">
                                    <a href="{{ route('tags.index') }}">Tags</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-md-10">
                            @yield('content')
                        </div>
                    </div>
                </div>

            @else

                @yield('content')

            @endauth
        </main>
    </div>


    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    @yield('scripts')
</body>
</html>