TaskManagerLaravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();


// Routes accessible only to admins and managers
Route::middleware(['auth', 'manager'])->group(function () {
    // Project Routes
    Route::get('projects/create', 'ProjectController@create')->name('projects.create');
    Route::post('projects', 'ProjectController@store')->name('projects.store');
    Route::put('projects/{project}', 'ProjectController@update')->name('projects.update');
    Route::delete('projects/{project}', 'ProjectController@destroy')->name('projects.destroy');
    Route::get('projects/{project}/edit', 'ProjectController@edit')->name('projects.edit');

    Route::get('users', 'UserController@index')->name('users.index');
});




// Routes accessible to all authenticated users
Route::middleware(['auth'])->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    // User route seems not to work if put in the user routes section
    Route::get('users/profile', 'UserController@editProfile')->name('users.edit-profile');
    Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    Route::put('users/{user}', 'UserController@update')->name('users.update');
    Route::get('users/notifications', 'UserController@notifications')->name('users.notifications');

    Route::get('projects', 'ProjectController@index')->name('projects.index');
    Route::get('projects/{project}', 'ProjectController@show')->name('projects.show');

    // Task Routes
    Route::get('tasks', 'TaskController@index')->name('tasks.index');
    Route::post('tasks', 'TaskController@store')->name('tasks.store');
    Route::get('tasks/create', 'TaskController@create')->name('tasks.create');
    Route::delete('tasks/{task}', 'TaskController@destroy')->name('tasks.destroy');
    Route::get('tasks/{task}', 'TaskController@show')->name('tasks.show');
    Route::put('tasks/{task}', 'TaskController@update')->name('tasks.update');
    Route::get('tasks/{task}/edit', 'TaskController@edit')->name('tasks.edit');

    // Tag Routes
    Route::resource('tags', 'TagController');
    Route::resource('comments', 'CommentController');

    // User Routes
    Route::get('users/{user}', 'UserController@show')->name('users.show');
    Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
});

// Routes accessible only to the admins
//Route::middleware(['auth', 'admin'])->group(function () {
//});
//
//

TaskManagerLaravel/app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Tag;
use App\Http\Requests\Tags\CreateTagRequest;
use App\Http\Requests\Tags\UpdateTagRequest;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $search = request()->query('search');
        if ($search) {
            $tags = Tag::where('name', 'LIKE', "%{$search}%")->paginate(10);
        } else {
            $tags = Tag::paginate(10);
        }
        return view('tags.index')->with('tags', $tags);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CreateTagRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTagRequest $request)
    {
        Tag::create([
            'name' => $request->name
        ]);

        session()->flash('success', 'Tag created successfully.');

        return redirect(route('tags.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('tags.create')->with('tag', $tag);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  UpdateTagRequest $request
     * @param  Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateTagRequest $request, Tag $tag)
    {
        $tag->update([
            'name' => $request->name
        ]);

        session()->flash('success', 'Tag updated successfully.');

        return redirect(route('tags.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Tag $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();

        session()->flash('success', 'Tag deleted successfully!');

        return redirect(route('tags.index'));
    }
}

TaskManagerLaravel/resources/views/tags/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="card card-default">
        <h3 class="card-header">
            {{ isset($tag) ? 'Edit Tag' : 'Create Tag' }}
        </h3>
        <div class="card-body">
            @include('partials.errors')
            <form id="tag-form" action="{{ isset($tag) ? route('tags.update', $tag->id) : route('tags.store') }}" method="POST">
                @csrf
                @if (isset($tag))
                    @method('PUT')
                @endif
                <div class="form-group">
                    <label for="name">Name</label>
                    <input id="name" type="text" class="form-control" name="name" value="{{ isset($tag) ? $tag->name : '' }}">
                </div>

                <div class="form-group">
                    <button type="submit" class="btn btn-success">{{ isset($tag) ? 'Update Tag' : 'Add Tag' }}</button>
                    <a href="{{ URL::previous() }}" class="btn btn-danger">Cancel</a>
                </div>
            </form>
        </div>
    </div>
@endsection

TaskManagerLaravel/resources/views/tags/index.blade.php
@extends('layouts.app')


@section('content')
    <div class="card card-default">
        <div class="card-header d-flex justify-content-between">
            <h3>Tags</h3>
            <div>
                <a href="{{ route('tags.create') }}" class="btn btn-success">Add Tag</a>
            </div>
        </div>
        <div class="card-body">
            @if ($tags->count() > 0)
            <h3>Search for a Tag</h3>
            <sup>Name</sup>
            <form class="input-group" action="{{ route('tags.index') }}" method="GET">
                <input type="text" class="form-control" name="search" placeholder="Search" value="{{ request()->query('search') }}">
            </form>
            <hr>
                <div class="d-flex justify-content-center">
                    {{ $tags->appends(['search' => request()->query('search')])->links() }}
                </div>
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Tasks</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($tags as $tag)
                        <tr>
                            <td>{{ $tag->name }}</td>
                            <td>
                                {{ $tag->tasks->count() }}
                            </td>
                            <td>
                                <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-success btn-sm">Edit</a>
                                <button class="btn btn-danger btn-sm" onclick="handleDelete({{ $tag->id }}, '{{ $tag->name }}')">Delete</button>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div class="d-flex justify-content-center">
                    {{ $tags->appends(['search' => request()->query('search')])->links() }}
                </div>
            @else
                <h3 class="text-center">No Tags yet</h3>
        @endif

        <!-- Modal -->
            <div class="modal fade" id="delete-tag-modal" tabindex="-1" role="dialog" aria-labelledby="delete-tag-modal-label" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <form id="delete-tag-form" action="" method="POST">
                        @csrf
                        @method('DELETE')
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="delete-tag-modal-title"></h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <p class="text-center text-bold">
                                    Are you sure you want to delete this tag?
                                </p>
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="btn btn-danger">Confirm</button>
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script>
        function handleDelete(id, name) {
            let form = document.querySelector('#delete-tag-form');
            let title = document.querySelector('#delete-tag-modal-title');

            title.textContent = `Delete Tag: ${name}`;

            form.action = `tags/${id}`;
            $('#delete-tag-modal').modal('show');
        }
    </script>

@endsection